apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-test
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: k8s-app-test
  template:
    metadata:
      labels:
        app: k8s-app-test
    spec:
      containers:
      - name: k8s-app-test
        image: k8s-app-test:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        # image: repo_uri
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-app-test
spec:
  selector:
    app: k8s-app-test
  ports:
  - port: 8080
    targetPort: 5000